// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB5EFix6trTqL09djnTIAjbZTzWj4-RFw',
    appId: '1:748478420271:web:82d9575e008b4ceceffdda',
    messagingSenderId: '748478420271',
    projectId: 'flutterfirebase-877e5',
    authDomain: 'flutterfirebase-877e5.firebaseapp.com',
    storageBucket: 'flutterfirebase-877e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCHOS9ONNidZvMHDzvF5Q27QVS5jnTMVs',
    appId: '1:748478420271:android:de6b78561d761f7deffdda',
    messagingSenderId: '748478420271',
    projectId: 'flutterfirebase-877e5',
    storageBucket: 'flutterfirebase-877e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzEULo5GixQ0_mMkTfUG-UkrFLEYPrp-s',
    appId: '1:748478420271:ios:65ab41b5097dfc52effdda',
    messagingSenderId: '748478420271',
    projectId: 'flutterfirebase-877e5',
    storageBucket: 'flutterfirebase-877e5.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzEULo5GixQ0_mMkTfUG-UkrFLEYPrp-s',
    appId: '1:748478420271:ios:65ab41b5097dfc52effdda',
    messagingSenderId: '748478420271',
    projectId: 'flutterfirebase-877e5',
    storageBucket: 'flutterfirebase-877e5.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB5EFix6trTqL09djnTIAjbZTzWj4-RFw',
    appId: '1:748478420271:web:20fa3fd8f6840bbeeffdda',
    messagingSenderId: '748478420271',
    projectId: 'flutterfirebase-877e5',
    authDomain: 'flutterfirebase-877e5.firebaseapp.com',
    storageBucket: 'flutterfirebase-877e5.firebasestorage.app',
  );
}
